[package]
name = "aead-benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
aes-gcm-siv = "0.11.1"
chacha20poly1305 = "0.10.1"

[[bench]]
name = "aead"
harness = false

[dev-dependencies]
criterion = "0.5.1"
